// Subject-specific questions shown during the teacher registration assessment.
// The assessment step selects the matching list and records each answer for review.
const subjectQuestions = {
  'Full Stack Web Development': [
    'How does the browser DOM differ from the HTML source, and how would you diagnose an event handler that works before a re-render but not after it?',
    'Explain the CSS box model and show how box-sizing: border-box changes the calculation of an element\'s rendered width.',
    'What is the difference between JavaScript closures and lexical scope, and give an example where a closure is useful in application code.',
    'In React, why can state updates appear asynchronous, and how would you safely update state when the next value depends on the previous value?',
    'Describe how you would design a Node.js REST endpoint that validates input, handles asynchronous database errors, and avoids exposing sensitive fields.',
  ],
  'Mobile App Development': [
    'Compare native, cross-platform, and progressive web applications in terms of runtime, platform APIs, performance, and maintenance trade-offs.',
    'How should a mobile app persist user data securely, and which kinds of data should not be stored in ordinary local preferences?',
    'Explain how an event loop and the UI thread interact on mobile; what symptoms occur when expensive work blocks the UI thread?',
    'How would you design network requests to handle intermittent connectivity, retries, duplicate submissions, and stale responses?',
    'Describe a practical strategy for testing responsive layouts and platform-specific behavior across devices with different screen sizes and OS versions.',
  ],
  'AI and Machine Learning': [
    'Explain the bias-variance trade-off and how training, validation, and test results can reveal overfitting.',
    'When would you choose precision, recall, F1 score, or ROC-AUC to evaluate a classifier, and how does class imbalance affect that choice?',
    'Describe gradient descent and explain how learning rate and feature scaling can affect convergence.',
    'What is data leakage? Give an example involving preprocessing or time-series data and explain how to prevent it.',
    'How would you compare a simple baseline model with a more complex model while accounting for interpretability, cost, and deployment constraints?',
  ],
  Cybersecurity: [
    'Explain the difference between authentication and authorization, and describe how a signed JWT can be validated without making its claims confidential.',
    'How does parameterized SQL prevent injection, and why is input validation alone not a reliable substitute?',
    'Describe the purpose of password salting and adaptive hashing, and explain why a fast general-purpose hash is unsuitable for password storage.',
    'What are CSRF and XSS, how do their attack paths differ, and which mitigations address each one?',
    'Given a suspected credential compromise, what immediate containment and evidence-preservation steps would you take before restoring service?',
  ],
  English: [
    'Explain the grammatical difference between the present perfect sentence I have taught and the simple past sentence I taught, and provide an example for intermediate learners.',
    'How would you teach subject-verb agreement in a sentence with an intervening prepositional phrase, for example The quality of the answers ...?',
    'Design a short communicative activity that develops speaking fluency while still giving learners useful, non-disruptive corrective feedback.',
    'How would you distinguish a learner\'s recurring grammatical error from a one-time performance mistake, and how should instruction respond to each?',
    'Explain how cohesion and coherence differ in writing, and identify one classroom activity for teaching each concept.',
  ],
  Arabic: [
    'كيف يساعد نظام الجذر والوزن الصرفي المتعلمين على استنتاج العلاقات بين الكلمات؟ اذكر أيضا حدا من حدود الاعتماد على الجذر وحده.',
    'كيف تؤثر علامات الإعراب في المعنى والوظائف النحوية داخل جملة عربية مضبوطة بالشكل؟',
    'صمم خطوات متدرجة لتعليم قاعدة الحروف الشمسية والقمرية في النطق وكتابة أداة التعريف.',
    'كيف تشرح الفرق بين المثنى وجموع التكسير وجمعي المذكر والمؤنث السالمين، مع بيان أثر المطابقة في الجملة؟',
    'ما التحديات التي يطرحها الازدواج اللغوي عند تعليم العربية؟ وكيف تختار بين العربية الفصحى الحديثة واللهجات في مقرر دراسي؟',
  ],
  Amharic: [
    'የአማርኛ ፊደል ስርዓት ተነባቢና አናባቢ ድምፆችን እንዴት ያቀራርባል? ጀማሪዎች ያልተለመዱ ፊደላትን እንዲያነቡ የሚረዳ የትምህርት ቅደም ተከተል ግለጽ።',
    'በአማርኛ ግስ ላይ የሚታየው የገዢ አካል ምልክት በግልጽ የተጠቀሰ የርዕሰ ነገር ስም ጋር እንዴት ይዛመዳል?',
    'በአሁንና ባለፈ ጊዜ ምሳሌዎች በመጠቀም አሉታዊ አነጋገርን አመሠራረትና ትርጉም እንዴት ታስተምራለህ?',
    'ተፈጥሯዊ የክፍል ምሳሌዎችን በመጠቀም የአማርኛ የቃላት ቅደም ተከተልንና የመስተዋድዶችን ሚና ለማስተማር የሚያገለግል ዘዴ ግለጽ።',
    'ተማሪው በአማርኛ የሚቀላቀሉ ድምፆችን መለየትና በትክክል ማሰማት መቻሉን እንዴት ትገመግማለህ?',
  ],
  'Afaan Oromo': [
    'Ramaddii maqaa fi waliigalteen Afaan Oromoo keessatti bifa ibsituu fi gochimaa hima tokko keessatti akkamitti jijjiiru?',
    'Fakkeenya Afaan Oromoo walbira qabaman fayyadamuun hariiroo caas-lugaa agarsiisuuf xumura haal-sagalee akkamitti barsiista?',
    'Barattoonni dubbachiiftuu dheeraa fi dubbifamaa dachaa qabu sirriitti akka dubbisan gargaarsuuf tartiiba barnootaa ibsi.',
    'Barattoonni bifa gochimaa dhuunfaa fi yeroo waliin hiika isaa akka walqabsiisan, osoo bifa adda addaa qofa hin yaadatin, akkamitti barsiista?',
    'Jechoota jalqabaa hin burjaajessine, garuu garaagarummaa naannoo Afaan Oromoo bakka bu\'an filachuuf dubbisa fi dhaggeeffannaa akkamitti filatta?',
  ],
  Mathematics: [
    'A learner claims that multiplying two negative numbers gives a negative result. Use a number pattern or another mathematical argument to diagnose and correct the misconception.',
    'Prove that the sum of the interior angles of a Euclidean triangle is 180 degrees, and describe how you would adapt the explanation for visual learners.',
    'A class has a mean score of 72. One score of 48 is corrected to 84. Without recalculating every score, how does the mean change, and why?',
    'Solve a quadratic equation by completing the square and explain how that method reveals the relationship to the vertex form of a parabola.',
    'How would you distinguish correlation from causation when teaching statistics, and design a small data investigation that exposes the difference?',
  ],
  Physics: [
    'A block moves at constant velocity on a rough horizontal surface. Draw or describe the free-body diagram and explain how Newton\'s laws account for the net force.',
    'Explain why terminal velocity occurs during a fall through a fluid, relating drag, weight, acceleration, and resultant force.',
    'Two resistors are connected in parallel to an ideal battery. Derive how the equivalent resistance compares with either individual resistance.',
    'Describe how you would use a velocity-time graph to determine displacement and acceleration, including what a negative gradient represents.',
    'A wave enters a medium where its speed decreases. Explain what happens to its frequency and wavelength and justify the result physically.',
  ],
  Biology: [
    'Explain how a change in DNA sequence can alter a protein, and why some mutations have no effect on the resulting phenotype.',
    'Compare meiosis and mitosis in chromosome number, genetic variation, and biological purpose.',
    'How do enzyme concentration, substrate concentration, and temperature affect reaction rate, and why can very high temperature reduce activity?',
    'Trace energy and matter through a food web and explain why energy transfer between trophic levels is inefficient.',
    'Design a controlled experiment to test how light intensity affects photosynthesis, identifying independent, dependent, and controlled variables.',
  ],
  Chemistry: [
    'Use electron configuration to explain why elements in the same group often have similar chemical properties.',
    'A reaction is at dynamic equilibrium. Explain what happens to forward and reverse reaction rates when temperature is changed, and how equilibrium position may shift.',
    'How would you determine the limiting reactant from given reactant masses, and why must the balanced equation be used before comparing amounts?',
    'Compare ionic and covalent bonding in terms of electron behavior and explain how bonding relates to electrical conductivity in different states.',
    'Describe how a buffer resists pH change when a small amount of acid is added, using the conjugate acid-base pair in your explanation.',
  ],
  'Business Management': [
    'How would you use a contribution margin and break-even analysis to evaluate a proposed product when fixed costs and variable costs are known?',
    'Compare functional and matrix organizational structures, including a situation where each structure is likely to create coordination problems.',
    'A team consistently misses delivery targets despite high individual output. How would you investigate whether the issue is capacity, workflow, incentives, or dependencies?',
    'Explain how working capital differs from profit and give an example of a profitable business facing a cash-flow crisis.',
    'How would you translate a strategic objective into measurable KPIs while avoiding metrics that reward behavior contrary to the objective?',
  ],
  Economics: [
    'Using supply and demand, distinguish a movement along a demand curve from a shift in demand, and predict the effect of each on equilibrium price and quantity.',
    'Explain why a binding price ceiling can create a shortage and identify conditions that affect the size of the shortage.',
    'How does price elasticity of demand influence total revenue when a firm raises its price?',
    'Distinguish a negative externality from a public good and explain one policy instrument that can address each market failure.',
    'Explain how expansionary monetary policy can affect output and inflation, including why transmission may be delayed or incomplete.',
  ],
  Entrepreneurship: [
    'How would you test a risky customer-problem assumption with a minimum viable experiment before investing in a full product build?',
    'Explain the difference between revenue, gross margin, and contribution margin, and how each informs a startup\'s unit economics.',
    'A startup has a high customer acquisition cost and strong retention. Which cohort and payback metrics would you examine before increasing marketing spend?',
    'How would you distinguish a scalable business model from a service that grows only by adding labor in proportion to revenue?',
    'Describe how you would prioritize product features when customer requests conflict and engineering capacity is limited.',
  ],
  Leadership: [
    'A high-performing employee resists a change that the team needs. How would you diagnose the source of resistance and build commitment without suppressing valid concerns?',
    'Describe how you would delegate a high-stakes task while providing accountability without taking the work back from the person.',
    'How should a leader respond when team performance data conflicts with their own impression of who is contributing most?',
    'Explain the difference between consensus and alignment, and identify when a leader should seek each before making a decision.',
    'Give a framework for delivering feedback about repeated missed commitments that is specific, fair, and oriented toward improvement.',
  ],
  'Communication Skills': [
    'How would you adapt the same technical explanation for a specialist audience and a non-specialist audience without changing its factual meaning?',
    'During a disagreement, how can a speaker distinguish a person\'s stated position from the underlying interest and use that distinction to move the discussion forward?',
    'What makes a question genuinely open-ended, and how would you use follow-up questions to avoid leading a participant toward your preferred answer?',
    'Describe a structure for communicating a complex recommendation to decision-makers, including evidence, uncertainty, risks, and a clear request.',
    'How would you identify and reduce barriers to understanding in a multilingual meeting where participants have different levels of fluency?',
  ],
}

export default subjectQuestions